[env:esp32cam]
platform = espressif32@7.0.1
board = esp32cam
framework = arduino
platform_packages =
    toolchain-xtensa-esp32 @ file://D:/Downloads/contentcreater-resources/esp32-cam/artifacts/toolchain.tar.gz
board_build.partitions = partitions.csv
monitor_speed = 115200
upload_speed = 460800
build_flags = -DCORE_DEBUG_LEVEL=3
